apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: shopkuber
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: shopkuber/orders:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: shopkuber-config
            - secretRef:
                name: shopkuber-secrets
          volumeMounts:
            - name: jwt-keys
              mountPath: /keys
              readOnly: true
          readinessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: "128Mi"
              cpu: "150m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: jwt-keys
          secret:
            secretName: jwt-keys
